import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import Providers from "@/context/Providers";

import RecoilRootProvider from "@/context/RecoilRootProvider";
import { ThemeProvider } from "@/context/ThemeProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <Toaster />
            <RecoilRootProvider>{children}</RecoilRootProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
