import "./globals.css";
import Providers from "@/context/Providers";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <Toaster />
        <body>{children}</body>
      </Providers>
    </html>
  );
}
